name: Github-CI Push/PR

env:
  DOCKER_BUILDX: "0.3.1"

on:
  push:
  pull_request:

jobs:
  cookie-cutter-osparc:
    name: testing cookie-cutter-osparc
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [3.8]
        os: [ubuntu-20.04]
        docker_buildx: [v0.5.1]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: setup docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: ${{ matrix.docker_buildx }}
          driver: docker
      - name: setup python environment
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: show versions
        run: ./ci/helpers/show_system_versions.bash
      - uses: actions/cache@v3.0.5
        name: getting cached data
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: set dev environs
        run: make devenv
      - name: test cookiecutter
        run: |
          source .venv/bin/activate
          pytest --cov=cookiecutter-osparc-service --durations=10 --cov-append --color=yes --cov-report=term-missing --cov-report=xml --cov-config=.coveragerc -vv tests
